POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "aj",
    "number": "044-123456"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "+44-723-1234-567"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Alan Turinguito"
}

