PUT http://localhost:3001/api/persons/62f778feaa0952263d78d3b3
Content-Type: application/json

{
    "name": "Honza",
    "number": "+123-456-789"
}

###

PUT http://localhost:3001/api/persons/62f778feaa0952263d78d3b1
Content-Type: application/json

{
    "name": "Honza",
    "number": "+123-456-789"
}