POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyZmZjOGVkNTEyYTVkYjgwMWJkNDhmNCIsImlhdCI6MTY2MTE1NDMyM30.hjG9cXChg7lcmPtr2gClNF6QnS8veqsHACiAQU7XqMo

{
    "title": "Painting saved my life",
    "author": "Emma Plunkett",
    "url": "https://emmaplunkett.art",
    "likes": 0
}