POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "root",
    "password": "T0pS3cr3t!"
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "crs1138",
    "password": "Fu11$t@ck0p3n"
}